creating users controller
myz96/sei-project-3 pull request #9
Opened 2023-04-22 06:05 UTC by davekuperman

creating users controller, and adding first name and last name to signup form

2023-04-22 06:19 UTC, myz96 requested changes
Line 44 in users.js
Use the createUser() function from models instead of line 44 to 58 since its already defined
Create custom errors, instead of pushing to Validation Messages (see quizzes.js line 29-33 for an example)

2023-04-23 02:48 UTC, myz96 approved these changes

2023-04-23 06:01 UTC, myz96 requested changes
It should be line 4: createUser
and for line 50 to 53, you can replace the whole thing with just createUser(first_name, last_name, email, password_hash)

2023-04-23 06:40 UTC, bjpfox commented
I have resolved the merge conflicts
@davekuperman  can you please use the github.com editor to update users.js per Michael's comments and then we can merge

2023-04-23 12:54 UTC, merged